version: "3.8"

services:
  bot:
    build: .
    command: python bot/bot.py
    env_file:
      - .env
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_NAME}
    container_name: postgres
